### ISSUE TITLE
Allergy list

### ISSUE THREAD

**Issue by Soritar** [Mithlond/mithlond-services#2]
The allergy list needs a worker over.

Suggested things:
- Possibility to get allergies for all those signed for an activity.
- Add allergy groups (if you for instance is allergic to all unions, you might not want to add each individual. Adding the group is also "safer", as you might miss one).
- Possibility to add or at least suggest new allergies (did a quick scan and I could, for instance, not find "Gluten". Other are probably missing too).
- Possibility to add/change allergies for others (as responsible for an activity, I might want to add someone who signed by other means than through the web, and allergies to them)

**Comment by lennartj** [comment]
Decently complex to get the food stuffs straight, but certainly doable.

**Comment by Soritar** [comment]
Maybe we should split this into several enhancements (like one per bullet point). Not all things need to be done at once (or have the same priority), and they are not really related (other than they all concern the allergies).

Thoughts?

**Comment by lennartj** [comment]
Yup. Lets split into several issues

**Comment by lennartj** [comment]
Split suggestion accepted.Closing this issue.
